'use client';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase-browser';
import type { Product } from '@/lib/types';
import { useRouter } from 'next/navigation';

const empty={name:'',description:'',price:'',currency:'₽',category:'',stock:'0',expiry_date:''};
export default function Admin(){const s=createClient();const r=useRouter();const [products,setProducts]=useState<Product[]>([]);const [f,setF]=useState<any>(empty);const [file,setFile]=useState<File|null>(null);const [msg,setMsg]=useState('');
async function load(){if(!s)return;const {data}=await s.from('products').select('*').order('created_at',{ascending:false});setProducts(data||[])}
useEffect(()=>{if(!s){r.push('/login');return;}(async()=>{const {data}=await s.auth.getUser();if(!data.user){r.push('/login');return;}await load();})();},[]);
async function save(){if(!s){setMsg('База данных не подключена');return;}setMsg('');let image_url='';if(file){const ext=file.name.split('.').pop();const path=`${Date.now()}.${ext}`;const up=await s.storage.from('product-images').upload(path,file);if(up.error){setMsg('Ошибка загрузки фото');return;}image_url=s.storage.from('product-images').getPublicUrl(path).data.publicUrl;}const {error}=await s.from('products').insert({name:f.name,description:f.description||null,price:Number(f.price),currency:f.currency||'₽',category:f.category||null,stock:Number(f.stock||0),expiry_date:f.expiry_date||null,image_url:image_url||null,is_active:true});if(error){setMsg(error.message);return;}setF(empty);setFile(null);setMsg('Товар добавлен');await load();}
async function del(id:string){if(!s)return;if(!confirm('Удалить товар?'))return;await s.from('products').delete().eq('id',id);await load();}
async function logout(){if(!s)return;await s.auth.signOut();r.push('/login')}
return <div className="admin-wrap"><aside className="sidebar"><h2>IHM Admin</h2><a href="/">Открыть каталог</a><button className="btn btn-secondary" onClick={logout}>Выйти</button></aside><main className="main"><div className="row between"><h1>Управление товарами</h1></div>{msg&&<div className="notice">{msg}</div>}<div className="card" style={{padding:18,marginBottom:22}}><h2>Добавить товар</h2><div className="field"><label>Название</label><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div className="field"><label>Описание</label><textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><div className="row"><div className="field" style={{flex:1}}><label>Цена</label><input type="number" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></div><div className="field" style={{width:120}}><label>Валюта</label><input value={f.currency} onChange={e=>setF({...f,currency:e.target.value})}/></div></div><div className="row"><div className="field" style={{flex:1}}><label>Категория</label><input value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></div><div className="field" style={{width:160}}><label>Количество</label><input type="number" value={f.stock} onChange={e=>setF({...f,stock:e.target.value})}/></div></div><div className="field"><label>Срок годности</label><input type="date" value={f.expiry_date} onChange={e=>setF({...f,expiry_date:e.target.value})}/></div><div className="field"><label>Фото</label><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><button className="btn btn-primary" onClick={save}>Сохранить товар</button></div><table className="table"><thead><tr><th>Фото</th><th>Название</th><th>Цена</th><th>Остаток</th><th></th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.image_url?<img src={p.image_url} style={{width:54,height:54,objectFit:'cover',borderRadius:8}}/>:'—'}</td><td>{p.name}</td><td>{p.price} {p.currency}</td><td>{p.stock}</td><td><button className="btn btn-danger" onClick={()=>del(p.id)}>Удалить</button></td></tr>)}</tbody></table></main></div>}
